1. Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [1]:
import numpy as np

In [2]:
import numpy as np

a = np.array([[
        
            [[9, 20], [13, 31], [8, 21], [13, 25], [9, 29], [15, 20], [10, 25]],
            [[13, 23], [9, 23], [13, 21], [-13, 32], [15, 25], [13, 31], [15, 29]],
            [[9, 24], [6, 26], [7, 30], [10, 30], [7, 30], [12, 22], [11, 32]],
            [[13, 30], [12, 26], [15, 26], [15, 29], [8, 25], [11, 27], [15, 24]]
        
    ],
    
    [
        
            [[6, 20], [13, 32], [13, 28], [15, 25], [10, 31], [12, 23], [13, 30]],
            [[9, 32], [6, 32], [8, 30], [7, 32], [7, 32], [14, 29], [9, 21]],
            [[14, 23], [11, 23], [14, 29], [15, 23], [15, 30], [10, 31], [13, 30]],
            [[13, 24], [10, 29], [12, 24], [6, 31], [13, 31], [13, 29], [7, 25]]
        
    ],
    [
        
            [[8, 18], [4, 19], [6, 18], [2, 22], [2, 18], [2, 5], [21, 5]],
            [[7, 20], [3, 21], [3, 20], [5, 20], [3, 18], [2, 6], [20, 6]],
            [[4, 19], [5, 21], [5, 18], [5, 21], [3, 19], [7, 6], [22, 4]],
            [[8, 22], [2, 20], [2, 22], [4, 20], [7, 22], [7, 2], [22, 5]]
        
    ],
    [
        
            [[7, 22], [10, 19], [-10, 18], [11, 20], [8, 20], [9, 71], [22, 10]],
            [[8, 22], [9, 21], [10, 22], [8, 19], [9, 18], [11, 11], [18, 11]],
            [[8, 21], [11, 20], [8, 22], [10, 18], [7, 18], [7, 7], [19, 7]],
            [[7, 19], [9, 22], [8, 22], [11, 18], [12, 22], [8, 11], [21, 8]]
        
    ]])
print(a)

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [  7  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
 

2. Write the dimensions and shape of the NumPy array that you have
created.


In [3]:
print(a.ndim)
print(a.shape)

4
(4, 4, 7, 2)


3. Print the daily temperatures for the first week of each month.


In [4]:
print(a[0:, 0, 0:, 0:])

[[[  9  20]
  [ 13  31]
  [  8  21]
  [ 13  25]
  [  9  29]
  [ 15  20]
  [ 10  25]]

 [[  6  20]
  [ 13  32]
  [ 13  28]
  [ 15  25]
  [ 10  31]
  [ 12  23]
  [ 13  30]]

 [[  8  18]
  [  4  19]
  [  6  18]
  [  2  22]
  [  2  18]
  [  2   5]
  [ 21   5]]

 [[  7  22]
  [ 10  19]
  [-10  18]
  [ 11  20]
  [  8  20]
  [  9  71]
  [ 22  10]]]


4. Print the temperatures for Tuesday of each month.


In [5]:
print(a[0:, 0:, 1, 0:])

[[[13 31]
  [ 9 23]
  [ 6 26]
  [12 26]]

 [[13 32]
  [ 6 32]
  [11 23]
  [10 29]]

 [[ 4 19]
  [ 3 21]
  [ 5 21]
  [ 2 20]]

 [[10 19]
  [ 9 21]
  [11 20]
  [ 9 22]]]


5. Print only the maximum temperature for all the weekdays of Dec and Feb.


In [6]:
print(a[1:4:2, 0:, 0:, 1])

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[22 19 18 20 20 71 10]
  [22 21 22 19 18 11 11]
  [21 20 22 18 18  7  7]
  [19 22 22 18 22 11  8]]]


6. Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees.


In [7]:
c=a[0, 0:, 0:, 0]

b=(a[0, 0:, 0:, 0]) < 8  #filtering mini temp less than 8 degrees.

print(c[b])

[-13   6   7   7]


In [8]:
# week2,Thur, -13
print(c) # returns 2D array


[[  9  13   8  13   9  15  10]
 [ 13   9  13 -13  15  13  15]
 [  9   6   7  10   7  12  11]
 [ 13  12  15  15   8  11  15]]


In [9]:
d= np.where(c<8)  # return indexes of values according to given condition in where func 
print(d)

(array([1, 2, 2, 2], dtype=int64), array([3, 1, 2, 4], dtype=int64))


In [10]:
weeks = ["week1", "week2", "week3", "week4"]
days = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"]

e=map(d, weeks, days)
print(list[e])

list[<map object at 0x00000201980CBF10>]


7. Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.


In [14]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 1]
s=(a[l, 0:, 0:, 1]) > 20
print(c[s])   #returns all those values of max temp who has crossed a threshold of 20 deg.

[32 28 25 31 23 30 32 32 30 32 32 29 21 23 23 29 23 30 31 30 24 29 24 31
 31 29 25 22 21 21 21 22 22 22]


In [15]:
print(c)  #returns 3D

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[18 19 18 22 18  5  5]
  [20 21 20 20 18  6  6]
  [19 21 18 21 19  6  4]
  [22 20 22 20 22  2  5]]]


In [18]:
d=np.where(c>20)  #return indexes
print(d)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 0, 1, 2, 2, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 3, 1, 1, 3, 0, 2, 4], dtype=int64))


In [26]:
# Get maximum temperatures for December and January
dec_max_temps = a[0, :, :, 1]
jan_max_temps = a[1, :, :, 1]

# Find the indices where max temperature has crossed the threshold in December
dec_indices = np.where(dec_max_temps > threshold)
print("the indices where max temperature has crossed the threshold in December: \n", dec_indices)

# Find the indices where max temperature has crossed the threshold in January
jan_indices = np.where(jan_max_temps > threshold)
print("the indices where max temperature has crossed the threshold in January: \n", jan_indices)

# Combine the indices from December and January
combined_indices = (dec_indices[0], dec_indices[1]) + (jan_indices[0], jan_indices[1])
print("Combine the indices from December and January\n", combined_indices)

# Get unique week numbers that have crossed the threshold
unique_week_numbers = np.unique(combined_indices[0])

# Print the week numbers that have crossed the threshold in December and/or January
for week_number in unique_week_numbers:
    print(f"Week {week_number + 1} has crossed the threshold in December and/or January.")

the indices where max temperature has crossed the threshold in December: 
 (array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
       3, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6], dtype=int64))
the indices where max temperature has crossed the threshold in January: 
 (array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6], dtype=int64))
Combine the indices from December and January
 (array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
       3, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6], dtype=int64), array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 