1. Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [1]:
import numpy as np

In [2]:
import numpy as np

temp = np.array([[
        
            [[9, 20], [13, 31], [8, 21], [13, 25], [9, 29], [15, 20], [10, 25]],
            [[13, 23], [9, 23], [13, 21], [-13, 32], [15, 25], [13, 31], [15, 29]],
            [[9, 24], [6, 26], [7, 30], [10, 30], [7, 30], [12, 22], [11, 32]],
            [[13, 30], [12, 26], [15, 26], [15, 29], [8, 25], [11, 27], [15, 24]]
        
    ],
    
    [
        
            [[6, 20], [13, 32], [13, 28], [15, 25], [10, 31], [12, 23], [13, 30]],
            [[9, 32], [6, 32], [8, 30], [7, 32], [7, 32], [14, 29], [9, 21]],
            [[14, 23], [11, 23], [14, 29], [15, 23], [15, 30], [10, 31], [13, 30]],
            [[13, 24], [10, 29], [12, 24], [6, 31], [13, 31], [13, 29], [7, 25]]
        
    ],
    [
        
            [[8, 18], [4, 19], [6, 18], [2, 22], [2, 18], [2, 5], [21, 5]],
            [[7, 20], [3, 21], [3, 20], [5, 20], [3, 18], [2, 6], [20, 6]],
            [[4, 19], [5, 21], [5, 18], [5, 21], [3, 19], [7, 6], [22, 4]],
            [[8, 22], [2, 20], [2, 22], [4, 20], [7, 22], [7, 2], [22, 5]]
        
    ],
    [
        
            [[7, 22], [10, 19], [-10, 18], [11, 20], [8, 20], [9, 71], [22, 10]],
            [[8, 22], [9, 21], [10, 22], [8, 19], [9, 18], [11, 11], [18, 11]],
            [[8, 21], [11, 20], [8, 22], [10, 18], [7, 18], [7, 7], [19, 7]],
            [[7, 19], [9, 22], [8, 22], [11, 18], [12, 22], [8, 11], [21, 8]]
        
    ]])
print(temp)

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [  7  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
 

In [3]:
print(temp.ndim)
print(temp.shape)

4
(4, 4, 7, 2)
