# NUMPY

In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
# myarr = np.array([1,2,3,4,5] , np.int64)
myarr = np.array([[1,2,3,4,5]], np.int64)

In [4]:
myarr[0]

array([1, 2, 3, 4, 5], dtype=int64)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0, 1]

2

In [8]:
myarr[0,1] = 45  #updating value

In [9]:
myarr

array([[ 1, 45,  3,  4,  5]], dtype=int64)

# Array creation : Conversion from other python structures

In [10]:
listarray = np.array([[1,2,3], [5,8,9], [0,2,4]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 9],
       [0, 2, 4]])

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.size

9

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,10,4)

In [21]:
lspace

array([ 1.,  4.,  7., 10.])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521510e-306, 4.22774898e-307, 1.06810539e-306],
       [7.56599807e-307, 8.90104239e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.60217812e-306,
        1.37961370e-306, 1.69118515e-306, 1.11258277e-307],
       [1.05700515e-307, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 9.79107193e-307]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([ 1.,  4.,  7., 10.])

In [26]:
ide = np.identity(45) #provide 45X45 matrix 

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
 arr = arr.reshape(3, 33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
 arr = arr.ravel()  # make 1D array now 

In [34]:
arr.shape

(99,)

In [35]:
x = [[2,3,4], [5,6,7], [0,1,2]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [38]:
ar.sum(axis = 0)  #calculate sum columnwise

array([ 7, 10, 13])

In [39]:
ar.sum(axis = 1) #calculate sum rowwise

array([ 9, 18,  3])

In [40]:
ar.T  #transpose the matrix

array([[2, 5, 0],
       [3, 6, 1],
       [4, 7, 2]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

2
3
4
5
6
7
0
1
2


In [43]:
ar.ndim  # no. of dim

2

In [44]:
ar.size  # 3X3

9

In [45]:
ar.nbytes

36

In [46]:
one = np.array([2,3,4,545,23,22])

In [47]:
one.argmax()  #gives index at max value

3

In [48]:
one.argmin()

0

In [49]:
one.argsort() #provides indexes when sorting in ascending order

array([0, 1, 2, 5, 4, 3], dtype=int64)

In [50]:
ar   # for 2D dim

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [51]:
ar.argmin()

6

In [52]:
ar.argmax()

5

In [53]:
ar.argmax(axis = 0)  #gives index of max value in each col

array([1, 1, 1], dtype=int64)

In [54]:
ar.argmax(axis = 1) # givs index of max value in each row

array([2, 2, 2], dtype=int64)

In [55]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [56]:
ar

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [57]:
ar1 = np.array([[2,3,4], [4,3,1], [5,6,8]])
ar1

array([[2, 3, 4],
       [4, 3, 1],
       [5, 6, 8]])

In [58]:
ar + ar1  #adding two matrix

array([[ 4,  6,  8],
       [ 9,  9,  8],
       [ 5,  7, 10]])

In [59]:
[234, 78] + [4, 5] #here we can not add in list

[234, 78, 4, 5]

In [60]:
ar * ar1 #can be performed any operations

array([[ 4,  9, 16],
       [20, 18,  7],
       [ 0,  6, 16]])

In [61]:
np.sqrt(ar)  # square root of each element in ar matrix

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [0.        , 1.        , 1.41421356]])

In [62]:
ar.sum()

30

In [63]:
ar.max()

7

In [64]:
ar.min()

0

In [65]:
ar


array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [66]:
np.where(ar>5) #gives index where element is greater than 5

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [70]:
ar[2,0]=0

In [71]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [72]:
import sys

In [73]:
py_ar = [0,4,55,2]

In [74]:
np_ar = np.array(py_ar)

In [75]:
sys.getsizeof(1) * len(py_ar) #takes more size

112

In [76]:
np_ar.itemsize * np_ar.size  #memory efficient in numpy

16

In [77]:
ar.tolist()  # makes list of numpy array

[[2, 3, 4], [5, 6, 7], [0, 1, 2]]

In [78]:
dir(np)   #gives all func of numpy lib

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [79]:
a = np.array([2,3,4,5])

In [80]:
a

array([2, 3, 4, 5])

In [81]:
print(a)

[2 3 4 5]


In [82]:
a.shape  #returns tuples and here , comma is used to separate from the bracket

(4,)

In [83]:

a1=np.array([[[2]]])

In [84]:
a1.shape

(1, 1, 1)

In [85]:
a1.ndim

3

In [86]:
a1

array([[[2]]])

In [87]:
print(a1)

[[[2]]]


create an array of shape (5,4) and (3,1,2)

In [88]:

a= np.array([[1,2,3,4], [3,4,5,6],[2,3,8,6], [5,3,2,1],[3,4,5,7]])

In [89]:
a.shape

(5, 4)

In [90]:
a= np.array([[[2,3]],[[4,5]],[[5,8]]])
a.shape

(3, 1, 2)

In [91]:
z=np.zeros(5, dtype=np.int8)

In [92]:
print(z)

[0 0 0 0 0]


In [93]:
z=np.ones((3,4), dtype=np.int8)
print(z)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [94]:
z=np.linspace(1,2,num=5, endpoint=False)
z

array([1. , 1.2, 1.4, 1.6, 1.8])

In [95]:
z[1] #array are only values mutable not for size in numpy

1.2

In [96]:
z=np.array([np.arange(1,5), np.arange(11,15)])
print(z)

[[ 1  2  3  4]
 [11 12 13 14]]


In [97]:
z[0]

array([1, 2, 3, 4])

In [98]:
z[1,0]  # or z[1][0] both gives same answer

11

In [99]:
z[0:, 1:3]

array([[ 2,  3],
       [12, 13]])

In [100]:
# s=np.array([[[1,2,3],[,2,3,4],[3,4,5],[4,5,56]],[[3,4,5],[5,6,7],[],[]],[[],[],[],[]]]) # 3,4,3

In [101]:
s=np.array(np.arange(1,37))

In [102]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [103]:
f=s.reshape(3,4,3)
print(f)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [104]:
print(f[0:3:2, 1:4:2, 1])

[[ 5 11]
 [29 35]]


In [105]:
a=np.array([np.arange(1,6), np.arange(11,16)])

In [106]:
print(a)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [107]:
l=[1,2,3]   #here indexs is used in l for slicing
print(a[0, l])  #a[0, 1:4]

[2 3 4]


In [108]:
print(a[0, 1:4])

[2 3 4]


In [109]:
a = np.array([2,3,5,3,4,7,6,9])
print(a)

[2 3 5 3 4 7 6 9]


In [110]:
#print elements in a where element is greater than 3
b=a>3
print(b)  # gives array of boolean values

[False False  True False  True  True  True  True]


In [111]:
print(a[b])

[5 4 7 6 9]


In [112]:
b=a.reshape(2,4)
print(b)

[[2 3 5 3]
 [4 7 6 9]]


In [113]:
# if we change in the b  variable then changes can also be view in a variable because they both share same  memory location.
b[0]=44
print(b)

[[44 44 44 44]
 [ 4  7  6  9]]


In [114]:
print(a)

[44 44 44 44  4  7  6  9]


In [115]:
b=a.reshape(2,4).copy()  #now here if we change in b then the a maintain its original values.

In [116]:
print(b)

[[44 44 44 44]
 [ 4  7  6  9]]


In [117]:
avg=np.mean(b, dtype=np.float32, axis=1) #aggregate function in numpy
print(avg)
print(round(3.14, 1))

[44.   6.5]
3.1


In [118]:
# where condition in aggregate function
a=np.array([[5,2,3], [4,7,8], [4,6,7]])
print(a.mean())
print(a.mean(where = [[True], [False], [False]]))  #here True for first row

5.111111111111111
3.3333333333333335


In [119]:
# mean, mode, median
# outliers only affect in mean
# outliers are extreme values

In [120]:
#flatten() and ravel()
a=np.arange(1,37).reshape(4,9)
c=a.flatten()  #convert into 1D from 2D in row-wise, mostly flatten func is used in deep learning
a.flatten(order='F') # F for column-wise, C for row-wise, K for memory-wise
print(c)
#here if we change in c then changes is not reflected in a as it pass the copy to the c variable.
#so we can use ravel() func instead of using flatten()
# ravel() is more faster than flatten func
# if we use ravel() then whatever we change in c then it will reflected in the a variable also

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [127]:
#concatenate in 1D array is by default axis=0 we can not use axis = 1
#concatenate in 2D array is can be axis 0 or 1
a=np.arange(1,7).reshape(2,3)
b=np.arange(11,17).reshape(2,3)

c=np.concatenate((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [129]:
c[0,2]=5
print(c[0,2])

5


In [131]:
print(a)

[[1 2 3]
 [4 5 6]]


In [132]:
c=np.stack((a,b), axis=1)  
print(c)  #return 3D array for better understanding of concatenating

[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]]


In [138]:
a=np.arange(1,28).reshape(3,3,3)
b=np.arange(11,38).reshape(3,3,3)

c=np.hstack((a,b))  
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]
  [14 15 16]
  [17 18 19]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [20 21 22]
  [23 24 25]
  [26 27 28]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [29 30 31]
  [32 33 34]
  [35 36 37]]]


In [140]:
a=np.arange(1,28)
s=np.split(a,3)
print(s)

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24, 25, 26, 27])]
