# NUMPY

In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
# myarr = np.array([1,2,3,4,5] , np.int64)
myarr = np.array([[1,2,3,4,5]], np.int64)

In [4]:
myarr[0]

array([1, 2, 3, 4, 5], dtype=int64)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0, 1]

2

In [8]:
myarr[0,1] = 45  #updating value

In [9]:
myarr

array([[ 1, 45,  3,  4,  5]], dtype=int64)

# Array creation : Conversion from other python structures

In [11]:
listarray = np.array([[1,2,3], [5,8,9], [0,2,4]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 9],
       [0, 2, 4]])

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.size

9

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.shape

(2, 5)

In [20]:
rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1,10,4)

In [27]:
lspace

array([ 1.,  4.,  7., 10.])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521510e-306, 4.22774898e-307, 1.06810539e-306],
       [7.56599807e-307, 8.90104239e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 8.45610231e-307, 9.34601642e-307],
       [1.86918699e-306, 1.69120281e-306, 2.22522597e-306,
        1.33511969e-306, 8.90071135e-308, 8.45610231e-307]])

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([ 1.,  4.,  7., 10.])

In [30]:
ide = np.identity(45) #provide 45X45 matrix 

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
 arr = arr.reshape(3, 33)

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
 arr = arr.ravel()  # make 1D array now 

In [42]:
arr.shape

(99,)

In [43]:
x = [[2,3,4], [5,6,7], [0,1,2]]

In [44]:
ar = np.array(x)

In [48]:
ar

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [45]:
ar.sum(axis = 0)  #calculate sum columnwise

array([ 7, 10, 13])

In [46]:
ar.sum(axis = 1) #calculate sum rowwise

array([ 9, 18,  3])

In [47]:
ar.T  #transpose the matrix

array([[2, 5, 0],
       [3, 6, 1],
       [4, 7, 2]])

In [49]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

2
3
4
5
6
7
0
1
2


In [53]:
ar.ndim  # no. of dim

2

In [54]:
ar.size  # 3X3

9

In [55]:
ar.nbytes

36

In [56]:
one = np.array([2,3,4,545,23,22])

In [57]:
one.argmax()  #gives index at max value

3

In [58]:
one.argmin()

0

In [59]:
one.argsort() #provides indexes when sorting in ascending order

array([0, 1, 2, 5, 4, 3], dtype=int64)

In [60]:
ar   # for 2D dim

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [62]:
ar.argmin()

6

In [63]:
ar.argmax()

5

In [64]:
ar.argmax(axis = 0)  #gives index of max value in each col

array([1, 1, 1], dtype=int64)

In [65]:
ar.argmax(axis = 1) # givs index of max value in each row

array([2, 2, 2], dtype=int64)

In [66]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [67]:
ar

array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [70]:
ar1 = np.array([[2,3,4], [4,3,1], [5,6,8]])
ar1

array([[2, 3, 4],
       [4, 3, 1],
       [5, 6, 8]])

In [71]:
ar + ar1  #adding two matrix

array([[ 4,  6,  8],
       [ 9,  9,  8],
       [ 5,  7, 10]])

In [72]:
[234, 78] + [4, 5] #here we can not add in list

[234, 78, 4, 5]

In [73]:
ar * ar1 #can be performed any operations

array([[ 4,  9, 16],
       [20, 18,  7],
       [ 0,  6, 16]])

In [74]:
np.sqrt(ar)  # square root of each element in ar matrix

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [0.        , 1.        , 1.41421356]])

In [75]:
ar.sum()

30

In [76]:
ar.max()

7

In [77]:
ar.min()

0

In [78]:
ar


array([[2, 3, 4],
       [5, 6, 7],
       [0, 1, 2]])

In [79]:
np.where(ar>5) #gives index where element is greater than 5

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [80]:
type(np.where(ar>5))

tuple

In [81]:
np.count_nonzero(ar)

8

In [82]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [83]:
ar[2,0]=0

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [85]:
import sys

In [86]:
py_ar = [0,4,55,2]

In [87]:
np_ar = np.array(py_ar)

In [88]:
sys.getsizeof(1) * len(py_ar) #takes more size

112

In [89]:
np_ar.itemsize * np_ar.size  #memory efficient in numpy

16

In [93]:
ar.tolist()  # makes list of numpy array

[[2, 3, 4], [5, 6, 7], [0, 1, 2]]